#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <errno.h>
#include <unistd.h>
#include <libgen.h>

#include "assets-error.h"
#include "assets-logging.h"

#ifdef HAS_EMBEDDED_DATA
#include "mz.h"
#include "mz_zip.h"
#include "mz_strm.h"
#include "mz_strm_mem.h"
#include "mz_zip_rw.h"
#include "mz_crypt.h"

// External symbols from embedded files (generated by objcopy)
extern const char _binary_ruby_stdlib_zip_start[];
extern const char _binary_ruby_stdlib_zip_end[];
extern const char _binary_ruby_stdlib_ext_zip_start[];
extern const char _binary_ruby_stdlib_ext_zip_end[];
extern const char _binary_fifo_interpreter_rb_start[];
extern const char _binary_fifo_interpreter_rb_end[];

// Manifest file configuration
#define MANIFEST_FILE ".embedded_manifest"
#define RUBY_VERSION "3.1.0"

// Manifest structure to track installed files
typedef struct {
    char version[128];           // Auto-generated version from CRC32 hash
    uint32_t ruby_stdlib_zip_crc32;
    uint32_t ruby_stdlib_ext_zip_crc32;
    uint32_t fifo_interpreter_rb_crc32;
    size_t ruby_stdlib_zip_size;
    size_t ruby_stdlib_ext_zip_size;
    size_t fifo_interpreter_rb_size;
} Manifest;

// Helper function to create directories recursively
static int create_directories(const char *path) {
    char *path_copy = strdup(path);
    char *dir = dirname(path_copy);

    struct stat st = {0};
    if (stat(dir, &st) == -1) {
        // Try to create parent directories first
        if (create_directories(dir) != 0) {
            free(path_copy);
            return -1;
        }

        if (mkdir(dir, 0755) != 0 && errno != EEXIST) {
            ASSETS_ERROR_LOG("Failed to create directory %s: %s", dir, strerror(errno));
            free(path_copy);
            return -1;
        }
    }

    free(path_copy);
    return 0;
}

// Compute CRC32 of binary data using minizip's implementation
static uint32_t compute_crc32(const void *data, size_t size) {
    uint32_t crc = 0;
    const uint8_t *bytes = (const uint8_t*)data;

    // Process in chunks for efficiency
    crc = mz_crypt_crc32_update(crc, bytes, (int32_t)size);

    return crc;
}

// Generate auto-version string from CRC32 hashes
// Format: "3.1.0-auto-XXXXXXXX" where XXXXXXXX is XOR of all CRC32 values
static void generate_auto_version(char *version_buf, size_t buf_size,
                                   uint32_t crc1, uint32_t crc2, uint32_t crc3) {
    // Combine all CRC32 values using XOR
    uint32_t composite_hash = crc1 ^ crc2 ^ crc3;

    // Format as version string
    snprintf(version_buf, buf_size, "%s-auto-%08X", RUBY_VERSION, composite_hash);
}

// Simple INI-style manifest reader
static int read_manifest(const char *install_dir, Manifest *manifest) {
    char manifest_path[1024];
    snprintf(manifest_path, sizeof(manifest_path), "%s/%s", install_dir, MANIFEST_FILE);

    FILE *file = fopen(manifest_path, "r");
    if (!file) {
        return -1; // Manifest doesn't exist
    }

    char line[512];
    while (fgets(line, sizeof(line), file)) {
        // Skip comments and empty lines
        if (line[0] == '#' || line[0] == '\n' || line[0] == '\r') {
            continue;
        }

        // Parse key=value pairs
        char *equals = strchr(line, '=');
        if (!equals) continue;

        *equals = '\0';
        char *key = line;
        char *value = equals + 1;

        // Trim newline from value
        char *newline = strchr(value, '\n');
        if (newline) *newline = '\0';
        newline = strchr(value, '\r');
        if (newline) *newline = '\0';

        // Parse values
        if (strcmp(key, "version") == 0) {
            strncpy(manifest->version, value, sizeof(manifest->version) - 1);
        } else if (strcmp(key, "ruby_stdlib_zip_crc32") == 0) {
            manifest->ruby_stdlib_zip_crc32 = (uint32_t)strtoul(value, NULL, 16);
        } else if (strcmp(key, "ruby_stdlib_ext_zip_crc32") == 0) {
            manifest->ruby_stdlib_ext_zip_crc32 = (uint32_t)strtoul(value, NULL, 16);
        } else if (strcmp(key, "fifo_interpreter_rb_crc32") == 0) {
            manifest->fifo_interpreter_rb_crc32 = (uint32_t)strtoul(value, NULL, 16);
        } else if (strcmp(key, "ruby_stdlib_zip_size") == 0) {
            manifest->ruby_stdlib_zip_size = (size_t)strtoull(value, NULL, 10);
        } else if (strcmp(key, "ruby_stdlib_ext_zip_size") == 0) {
            manifest->ruby_stdlib_ext_zip_size = (size_t)strtoull(value, NULL, 10);
        } else if (strcmp(key, "fifo_interpreter_rb_size") == 0) {
            manifest->fifo_interpreter_rb_size = (size_t)strtoull(value, NULL, 10);
        }
    }

    fclose(file);
    return 0;
}

// Write manifest file
static int write_manifest(const char *install_dir, const Manifest *manifest) {
    char manifest_path[1024];
    snprintf(manifest_path, sizeof(manifest_path), "%s/%s", install_dir, MANIFEST_FILE);

    FILE *file = fopen(manifest_path, "w");
    if (!file) {
        ASSETS_ERROR_LOG("Failed to create manifest file %s: %s", manifest_path, strerror(errno));
        return -1;
    }

    fprintf(file, "# Embedded Ruby VM Installation Manifest\n");
    fprintf(file, "# Auto-generated - do not edit manually\n");
    fprintf(file, "\n");
    fprintf(file, "version=%s\n", manifest->version);
    fprintf(file, "ruby_stdlib_zip_crc32=%08X\n", manifest->ruby_stdlib_zip_crc32);
    fprintf(file, "ruby_stdlib_ext_zip_crc32=%08X\n", manifest->ruby_stdlib_ext_zip_crc32);
    fprintf(file, "fifo_interpreter_rb_crc32=%08X\n", manifest->fifo_interpreter_rb_crc32);
    fprintf(file, "ruby_stdlib_zip_size=%zu\n", manifest->ruby_stdlib_zip_size);
    fprintf(file, "ruby_stdlib_ext_zip_size=%zu\n", manifest->ruby_stdlib_ext_zip_size);
    fprintf(file, "fifo_interpreter_rb_size=%zu\n", manifest->fifo_interpreter_rb_size);

    fclose(file);
    ASSETS_INFO_LOG("Manifest written: %s", manifest_path);
    return 0;
}

// Verify that extracted files exist and have correct sizes
static int verify_installation(const char *install_dir, const Manifest *manifest) {
    char file_path[1024];
    struct stat st;

    // Check fifo_interpreter.rb
    snprintf(file_path, sizeof(file_path), "%s/fifo_interpreter.rb", install_dir);
    if (stat(file_path, &st) != 0) {
        ASSETS_DEBUG_LOG("Verification failed: %s not found", file_path);
        return -1;
    }
    if ((size_t)st.st_size != manifest->fifo_interpreter_rb_size) {
        ASSETS_DEBUG_LOG("Verification failed: %s size mismatch (expected %zu, got %lld)",
                         file_path, manifest->fifo_interpreter_rb_size, (long long)st.st_size);
        return -1;
    }

    // Check that ruby directory exists (we extract zips, so just check directory)
    snprintf(file_path, sizeof(file_path), "%s/ruby", install_dir);
    if (stat(file_path, &st) != 0 || !S_ISDIR(st.st_mode)) {
        ASSETS_DEBUG_LOG("Verification failed: %s directory not found", file_path);
        return -1;
    }

    return 0;
}

// Extract a zip file from memory to a directory
static int extract_zip_from_memory(const char *zip_data, size_t zip_size, const char *extract_dir) {
    void *zip_handle = NULL;
    void *stream = NULL;
    int32_t err = MZ_OK;
    mz_zip_file *file_info = NULL;
    char extract_path[1024];
    FILE *output_file = NULL;
    void *buf = NULL;
    int32_t buf_size = 8192;
    int32_t bytes_read = 0;

    // Create memory stream
    stream = mz_stream_mem_create();
    if (!stream) {
        ASSETS_ERROR_LOG("Failed to create memory stream");
        return -1;
    }

    mz_stream_mem_set_buffer(stream, (void*)zip_data, zip_size);

    // Create zip reader
    zip_handle = mz_zip_reader_create();
    if (!zip_handle) {
        ASSETS_ERROR_LOG("Failed to create zip reader");
        goto cleanup;
    }

    // Open zip from memory stream
    err = mz_zip_reader_open(zip_handle, stream);
    if (err != MZ_OK) {
        ASSETS_ERROR_LOG("Failed to open zip from memory: %d", err);
        goto cleanup;
    }

    // Go to first entry
    err = mz_zip_reader_goto_first_entry(zip_handle);
    if (err != MZ_OK && err != MZ_END_OF_LIST) {
        ASSETS_ERROR_LOG("Failed to go to first zip entry: %d", err);
        goto cleanup;
    }

    buf = malloc(buf_size);
    if (!buf) {
        ASSETS_ERROR_LOG("Failed to allocate buffer");
        err = MZ_MEM_ERROR;
        goto cleanup;
    }

    // Extract all entries
    do {
        err = mz_zip_reader_entry_get_info(zip_handle, &file_info);
        if (err != MZ_OK) {
            ASSETS_ERROR_LOG("Failed to get zip entry info: %d", err);
            goto cleanup;
        }

        // Skip directories (check if filename ends with '/')
        if (file_info->filename[strlen(file_info->filename) - 1] == '/') {
            snprintf(extract_path, sizeof(extract_path), "%s/%s", extract_dir, file_info->filename);
            // Remove trailing slash
            extract_path[strlen(extract_path) - 1] = '\0';
            if (mkdir(extract_path, 0755) != 0 && errno != EEXIST) {
                ASSETS_ERROR_LOG("Failed to create directory %s: %s", extract_path, strerror(errno));
                // Continue with other files
            }
        } else {
            // Extract file
            snprintf(extract_path, sizeof(extract_path), "%s/%s", extract_dir, file_info->filename);

            // Create parent directories
            if (create_directories(extract_path) != 0) {
                ASSETS_ERROR_LOG("Failed to create parent directories for %s", extract_path);
                goto next_entry;
            }

            // Open entry for reading
            err = mz_zip_reader_entry_open(zip_handle);
            if (err != MZ_OK) {
                ASSETS_ERROR_LOG("Failed to open zip entry %s: %d", file_info->filename, err);
                goto next_entry;
            }

            // Open output file
            output_file = fopen(extract_path, "wb");
            if (!output_file) {
                ASSETS_ERROR_LOG("Failed to create file %s: %s", extract_path, strerror(errno));
                mz_zip_reader_entry_close(zip_handle);
                goto next_entry;
            }

            // Read and write file data
            do {
                bytes_read = mz_zip_reader_entry_read(zip_handle, buf, buf_size);
                if (bytes_read < 0) {
                    ASSETS_ERROR_LOG("Error reading from zip entry: %d", bytes_read);
                    break;
                }
                if (bytes_read > 0) {
                    if (fwrite(buf, 1, bytes_read, output_file) != (size_t)bytes_read) {
                        ASSETS_ERROR_LOG("Error writing to file %s: %s", extract_path, strerror(errno));
                        break;
                    }
                }
            } while (bytes_read > 0);

            fclose(output_file);
            output_file = NULL;

            mz_zip_reader_entry_close(zip_handle);

        }

next_entry:
        err = mz_zip_reader_goto_next_entry(zip_handle);
    } while (err == MZ_OK);

    if (err == MZ_END_OF_LIST) {
        err = MZ_OK; // Normal end of entries
    }

cleanup:
    if (buf) free(buf);
    if (zip_handle) {
        mz_zip_reader_close(zip_handle);
        mz_zip_reader_delete(&zip_handle);
    }
    mz_stream_mem_delete(&stream);

    return (err == MZ_OK) ? 0 : -1;
}

// Write binary data to a file
static int write_binary_file(const char *filename, const char *data, size_t size) {
    // Create parent directories
    if (create_directories(filename) != 0) {
        return -1;
    }

    FILE *file = fopen(filename, "wb");
    if (!file) {
        ASSETS_ERROR_LOG("Failed to create file %s: %s", filename, strerror(errno));
        return -1;
    }

    size_t written = fwrite(data, 1, size, file);
    fclose(file);

    if (written != size) {
        ASSETS_ERROR_LOG("Failed to write complete data to %s", filename);
        return -1;
    }

    ASSETS_DEBUG_LOG("Created: %s (%zu bytes)", filename, size);
    return 0;
}

// Main installation function
int install_embedded_files(const char *install_dir, AssetsError* error) {
    char full_path[1024];
    int result = 0;

    if (!install_dir) {
        assets_error_set(error, ASSETS_ERROR_INVALID_PARAM, NULL,
                        "Install directory cannot be NULL");
        return ASSETS_ERROR_INVALID_PARAM;
    }

    ASSETS_INFO_LOG("Installing embedded files to: %s", install_dir);

    // Create base installation directory
    if (mkdir(install_dir, 0755) != 0 && errno != EEXIST) {
        assets_error_set_errno(error, ASSETS_ERROR_MKDIR, install_dir,
                              "Failed to create install directory");
        return ASSETS_ERROR_MKDIR;
    }

    // Extract Ruby standard library ZIP
    ASSETS_INFO_LOG("Extracting Ruby standard library...");
    size_t ruby_stdlib_size = _binary_ruby_stdlib_zip_end - _binary_ruby_stdlib_zip_start;
    if (mkdir(install_dir, 0755) != 0 && errno != EEXIST) {
        assets_error_set_errno(error, ASSETS_ERROR_MKDIR, install_dir,
                              "Failed to create ruby-stdlib directory");
        result = ASSETS_ERROR_MKDIR;
    } else {
        if (extract_zip_from_memory(_binary_ruby_stdlib_zip_start, ruby_stdlib_size, install_dir) != 0) {
            assets_error_set(error, ASSETS_ERROR_ZIP_EXTRACT, "ruby-stdlib.zip",
                           "Failed to extract Ruby standard library");
            result = ASSETS_ERROR_ZIP_EXTRACT;
        }
    }

    ASSETS_INFO_LOG("Extracting Ruby standard library platform specifics...");
    size_t ruby_stdlib_ext_size = _binary_ruby_stdlib_ext_zip_end - _binary_ruby_stdlib_ext_zip_start;
    if (extract_zip_from_memory(_binary_ruby_stdlib_ext_zip_start, ruby_stdlib_ext_size, install_dir) != 0) {
        assets_error_set(error, ASSETS_ERROR_ZIP_EXTRACT, "ruby-stdlib-ext.zip",
                       "Failed to extract Ruby standard library extensions");
        result = ASSETS_ERROR_ZIP_EXTRACT;
    }

    // Write FIFO interpreter Ruby file
    ASSETS_INFO_LOG("Installing FIFO interpreter...");
    size_t fifo_interpreter_size = _binary_fifo_interpreter_rb_end - _binary_fifo_interpreter_rb_start;
    snprintf(full_path, sizeof(full_path), "%s/fifo_interpreter.rb", install_dir);
    if (write_binary_file(full_path, _binary_fifo_interpreter_rb_start, fifo_interpreter_size) != 0) {
        assets_error_set(error, ASSETS_ERROR_FILE_WRITE, full_path,
                       "Failed to install FIFO interpreter");
        result = ASSETS_ERROR_FILE_WRITE;
    }

    if (result == 0) {
        // Write manifest file after successful installation
        ASSETS_INFO_LOG("Writing installation manifest...");

        Manifest manifest = {0};

        // Compute CRC32 checksums of embedded data
        manifest.ruby_stdlib_zip_crc32 = compute_crc32(_binary_ruby_stdlib_zip_start, ruby_stdlib_size);
        manifest.ruby_stdlib_ext_zip_crc32 = compute_crc32(_binary_ruby_stdlib_ext_zip_start, ruby_stdlib_ext_size);
        manifest.fifo_interpreter_rb_crc32 = compute_crc32(_binary_fifo_interpreter_rb_start, fifo_interpreter_size);

        manifest.ruby_stdlib_zip_size = ruby_stdlib_size;
        manifest.ruby_stdlib_ext_zip_size = ruby_stdlib_ext_size;
        manifest.fifo_interpreter_rb_size = fifo_interpreter_size;

        // Generate auto-version from CRC32 hashes
        generate_auto_version(manifest.version, sizeof(manifest.version),
                              manifest.ruby_stdlib_zip_crc32,
                              manifest.ruby_stdlib_ext_zip_crc32,
                              manifest.fifo_interpreter_rb_crc32);

        if (write_manifest(install_dir, &manifest) != 0) {
            ASSETS_ERROR_LOG("Warning: Failed to write manifest file");
            // Don't fail installation due to manifest write failure
        }

        ASSETS_INFO_LOG("Installation completed successfully!");
        ASSETS_INFO_LOG("Version: %s", manifest.version);
    } else {
        ASSETS_ERROR_LOG("Installation completed with errors");
    }

    return result;
}

// Convenience function to get default install directory (can be customized)
const char* get_default_install_dir(void) {
    static char install_dir[1024];
    const char *cache_dir = getenv("XDG_CACHE_HOME");

    if (!cache_dir) {
        const char *home = getenv("HOME");
        if (home) {
            snprintf(install_dir, sizeof(install_dir), "%s/.cache/your_app", home);
        } else {
            // Fallback for Android or systems without HOME
            snprintf(install_dir, sizeof(install_dir), "/tmp/your_app_install");
        }
    } else {
        snprintf(install_dir, sizeof(install_dir), "%s/your_app", cache_dir);
    }

    return install_dir;
}

// Function to check if installation is needed (files exist and are valid)
int installation_needed(const char *install_dir, AssetsError* error) {
    Manifest current_manifest = {0};
    Manifest embedded_manifest = {0};

    if (!install_dir) {
        assets_error_set(error, ASSETS_ERROR_INVALID_PARAM, NULL,
                        "Install directory cannot be NULL");
        return ASSETS_ERROR_INVALID_PARAM;
    }

    // Build expected manifest from embedded data
    size_t ruby_stdlib_size = _binary_ruby_stdlib_zip_end - _binary_ruby_stdlib_zip_start;
    size_t ruby_stdlib_ext_size = _binary_ruby_stdlib_ext_zip_end - _binary_ruby_stdlib_ext_zip_start;
    size_t fifo_interpreter_size = _binary_fifo_interpreter_rb_end - _binary_fifo_interpreter_rb_start;

    ASSETS_DEBUG_LOG("Computing CRC32 checksums of embedded files...");
    embedded_manifest.ruby_stdlib_zip_crc32 = compute_crc32(_binary_ruby_stdlib_zip_start, ruby_stdlib_size);
    embedded_manifest.ruby_stdlib_ext_zip_crc32 = compute_crc32(_binary_ruby_stdlib_ext_zip_start, ruby_stdlib_ext_size);
    embedded_manifest.fifo_interpreter_rb_crc32 = compute_crc32(_binary_fifo_interpreter_rb_start, fifo_interpreter_size);

    embedded_manifest.ruby_stdlib_zip_size = ruby_stdlib_size;
    embedded_manifest.ruby_stdlib_ext_zip_size = ruby_stdlib_ext_size;
    embedded_manifest.fifo_interpreter_rb_size = fifo_interpreter_size;

    // Generate auto-version from CRC32 hashes
    generate_auto_version(embedded_manifest.version, sizeof(embedded_manifest.version),
                          embedded_manifest.ruby_stdlib_zip_crc32,
                          embedded_manifest.ruby_stdlib_ext_zip_crc32,
                          embedded_manifest.fifo_interpreter_rb_crc32);

    ASSETS_INFO_LOG("Embedded data version: %s", embedded_manifest.version);

    // Try to read existing manifest
    if (read_manifest(install_dir, &current_manifest) != 0) {
        ASSETS_INFO_LOG("No manifest found - installation needed");
        return 1; // No manifest = need installation
    }

    ASSETS_INFO_LOG("Installed version: %s", current_manifest.version);

    // Quick version check (fast path - avoids filesystem verification)
    if (strcmp(current_manifest.version, embedded_manifest.version) != 0) {
        ASSETS_INFO_LOG("Version mismatch - installation needed");
        ASSETS_DEBUG_LOG("  Expected: %s", embedded_manifest.version);
        ASSETS_DEBUG_LOG("  Found:    %s", current_manifest.version);
        return 1;
    }

    // Version matches - verify CRC32 values match (belt and suspenders)
    if (current_manifest.ruby_stdlib_zip_crc32 != embedded_manifest.ruby_stdlib_zip_crc32 ||
        current_manifest.ruby_stdlib_ext_zip_crc32 != embedded_manifest.ruby_stdlib_ext_zip_crc32 ||
        current_manifest.fifo_interpreter_rb_crc32 != embedded_manifest.fifo_interpreter_rb_crc32) {
        ASSETS_INFO_LOG("CRC32 mismatch detected - installation needed");
        return 1;
    }

    // Verify extracted files still exist and have correct sizes
    ASSETS_DEBUG_LOG("Verifying installation integrity...");
    if (verify_installation(install_dir, &current_manifest) != 0) {
        ASSETS_INFO_LOG("Installation verification failed - reinstallation needed");
        return 1;
    }

    ASSETS_INFO_LOG("Installation is up-to-date - skipping extraction");
    return 0; // Installation not needed
}

#else // !HAS_EMBEDDED_DATA

int install_embedded_files(const char *install_dir, AssetsError* error) {
    (void)install_dir; // Unused parameter
    assets_error_set(error, ASSETS_ERROR_NO_EMBEDDED_DATA, NULL,
                    "No embedded data available. Library was compiled without HAS_EMBEDDED_DATA");
    return ASSETS_ERROR_NO_EMBEDDED_DATA;
}

const char* get_default_install_dir(void) {
    return NULL;
}

int installation_needed(const char *install_dir, AssetsError* error) {
    (void)install_dir; // Unused parameter
    assets_error_set(error, ASSETS_ERROR_NO_EMBEDDED_DATA, NULL,
                    "No embedded data available. Library was compiled without HAS_EMBEDDED_DATA");
    return ASSETS_ERROR_NO_EMBEDDED_DATA;
}

#endif // HAS_EMBEDDED_DATA
