#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <errno.h>
#include <unistd.h>
#include <libgen.h>

#if defined(__linux__) || defined(__APPLE__)
#include <dlfcn.h>
#endif

#include "install.h"
#include "assets-error.h"
#include "assets-logging.h"

#ifdef HAS_EMBEDDED_DATA
#include "mz.h"
#include "mz_zip.h"
#include "mz_strm.h"
#include "mz_strm_mem.h"
#include "mz_zip_rw.h"
#include "mz_crypt.h"

// External symbols from embedded files (generated by objcopy)
extern const char _binary_ruby_stdlib_zip_start[];
extern const char _binary_ruby_stdlib_zip_end[];
extern const char _binary_ruby_stdlib_ext_zip_start[];
extern const char _binary_ruby_stdlib_ext_zip_end[];
// Note: fifo_interpreter.rb has been moved to libembedded-ruby.so

// External symbols for embedded native libraries (Phase 2)
#ifdef HAS_EMBEDDED_NATIVE_LIBS
extern const char _binary_libruby_so_start[];
extern const char _binary_libruby_so_end[];
extern const char _binary_libssl_so_start[];
extern const char _binary_libssl_so_end[];
extern const char _binary_libcrypto_so_start[];
extern const char _binary_libcrypto_so_end[];
extern const char _binary_libreadline_so_start[];
extern const char _binary_libreadline_so_end[];
extern const char _binary_libhistory_so_start[];
extern const char _binary_libhistory_so_end[];
extern const char _binary_libgdbm_so_start[];
extern const char _binary_libgdbm_so_end[];
extern const char _binary_libgdbm_compat_so_start[];
extern const char _binary_libgdbm_compat_so_end[];
extern const char _binary_libncurses_so_start[];
extern const char _binary_libncurses_so_end[];
extern const char _binary_libpanel_so_start[];
extern const char _binary_libpanel_so_end[];
extern const char _binary_libmenu_so_start[];
extern const char _binary_libmenu_so_end[];
extern const char _binary_libform_so_start[];
extern const char _binary_libform_so_end[];
extern const char _binary_libcurses_so_start[];
extern const char _binary_libcurses_so_end[];
#endif

// Manifest file configuration
#define MANIFEST_FILE ".embedded_manifest"
#define MANIFEST_FILE_JSON ".embedded_manifest.json"
#define RUBY_VERSION "3.1.0"

// Internal Manifest structure to track installed files
// This extends the public AssetsLayout with embedded data tracking
typedef struct {
    char version[128];           // Auto-generated version from CRC32 hash
    uint32_t ruby_stdlib_zip_crc32;
    uint32_t ruby_stdlib_ext_zip_crc32;
    size_t ruby_stdlib_zip_size;
    size_t ruby_stdlib_ext_zip_size;

    // Native library tracking
    char platform[64];
    char native_libs_dir[512];
    int native_lib_count;
    NativeLibInfo native_libs[MAX_NATIVE_LIBS];
} Manifest;

// Helper function to create directories recursively
static int create_directories(const char *path) {
    char *path_copy = strdup(path);
    char *dir = dirname(path_copy);

    struct stat st = {0};
    if (stat(dir, &st) == -1) {
        // Try to create parent directories first
        if (create_directories(dir) != 0) {
            free(path_copy);
            return -1;
        }

        if (mkdir(dir, 0755) != 0 && errno != EEXIST) {
            ASSETS_ERROR_LOG("Failed to create directory %s: %s", dir, strerror(errno));
            free(path_copy);
            return -1;
        }
    }

    free(path_copy);
    return 0;
}

// Compute CRC32 of binary data using minizip's implementation
static uint32_t compute_crc32(const void *data, size_t size) {
    uint32_t crc = 0;
    const uint8_t *bytes = (const uint8_t*)data;

    // Process in chunks for efficiency
    crc = mz_crypt_crc32_update(crc, bytes, (int32_t)size);

    return crc;
}

// Generate auto-version string from CRC32 hashes
// Format: "3.1.0-auto-XXXXXXXX" where XXXXXXXX is XOR of all CRC32 values
static void generate_auto_version(char *version_buf, size_t buf_size,
                                   uint32_t crc1, uint32_t crc2) {
    // Combine all CRC32 values using XOR
    uint32_t composite_hash = crc1 ^ crc2;

    // Format as version string
    snprintf(version_buf, buf_size, "%s-auto-%08X", RUBY_VERSION, composite_hash);
}

// Simple INI-style manifest reader
static int read_manifest(const char *install_dir, Manifest *manifest) {
    char manifest_path[1024];
    snprintf(manifest_path, sizeof(manifest_path), "%s/%s", install_dir, MANIFEST_FILE);

    FILE *file = fopen(manifest_path, "r");
    if (!file) {
        return -1; // Manifest doesn't exist
    }

    char line[512];
    while (fgets(line, sizeof(line), file)) {
        // Skip comments and empty lines
        if (line[0] == '#' || line[0] == '\n' || line[0] == '\r') {
            continue;
        }

        // Parse key=value pairs
        char *equals = strchr(line, '=');
        if (!equals) continue;

        *equals = '\0';
        char *key = line;
        char *value = equals + 1;

        // Trim newline from value
        char *newline = strchr(value, '\n');
        if (newline) *newline = '\0';
        newline = strchr(value, '\r');
        if (newline) *newline = '\0';

        // Parse values
        if (strcmp(key, "version") == 0) {
            strncpy(manifest->version, value, sizeof(manifest->version) - 1);
        } else if (strcmp(key, "ruby_stdlib_zip_crc32") == 0) {
            manifest->ruby_stdlib_zip_crc32 = (uint32_t)strtoul(value, NULL, 16);
        } else if (strcmp(key, "ruby_stdlib_ext_zip_crc32") == 0) {
            manifest->ruby_stdlib_ext_zip_crc32 = (uint32_t)strtoul(value, NULL, 16);
        } else if (strcmp(key, "ruby_stdlib_zip_size") == 0) {
            manifest->ruby_stdlib_zip_size = (size_t)strtoull(value, NULL, 10);
        } else if (strcmp(key, "ruby_stdlib_ext_zip_size") == 0) {
            manifest->ruby_stdlib_ext_zip_size = (size_t)strtoull(value, NULL, 10);
        }
    }

    fclose(file);
    return 0;
}

// Write manifest in JSON format (new format)
static int write_manifest_json(const char *install_dir, const Manifest *manifest) {
    char manifest_path[1024];
    snprintf(manifest_path, sizeof(manifest_path), "%s/%s", install_dir, MANIFEST_FILE_JSON);

    FILE *file = fopen(manifest_path, "w");
    if (!file) {
        ASSETS_ERROR_LOG("Failed to create JSON manifest file %s: %s", manifest_path, strerror(errno));
        return -1;
    }

    fprintf(file, "{\n");
    fprintf(file, "  \"_comment\": \"Embedded Ruby VM Installation Manifest - Auto-generated\",\n");
    fprintf(file, "  \"version\": \"%s\",\n", manifest->version);
    fprintf(file, "  \"platform\": \"%s\",\n", manifest->platform);
    fprintf(file, "  \"ruby_assets\": {\n");
    fprintf(file, "    \"ruby_stdlib_zip\": {\n");
    fprintf(file, "      \"crc32\": \"%08X\",\n", manifest->ruby_stdlib_zip_crc32);
    fprintf(file, "      \"size\": %zu\n", manifest->ruby_stdlib_zip_size);
    fprintf(file, "    },\n");
    fprintf(file, "    \"ruby_stdlib_ext_zip\": {\n");
    fprintf(file, "      \"crc32\": \"%08X\",\n", manifest->ruby_stdlib_ext_zip_crc32);
    fprintf(file, "      \"size\": %zu\n", manifest->ruby_stdlib_ext_zip_size);
    fprintf(file, "    }\n");
    fprintf(file, "  },\n");
    fprintf(file, "  \"native_libs\": {\n");
    fprintf(file, "    \"directory\": \"%s\",\n", manifest->native_libs_dir);
    fprintf(file, "    \"count\": %d,\n", manifest->native_lib_count);
    fprintf(file, "    \"libraries\": [\n");

    for (int i = 0; i < manifest->native_lib_count; i++) {
        fprintf(file, "      {\n");
        fprintf(file, "        \"name\": \"%s\",\n", manifest->native_libs[i].name);
        fprintf(file, "        \"relative_path\": \"%s\",\n", manifest->native_libs[i].relative_path);
        fprintf(file, "        \"crc32\": \"%08X\",\n", manifest->native_libs[i].crc32);
        fprintf(file, "        \"size\": %zu\n", manifest->native_libs[i].size);
        fprintf(file, "      }%s\n", (i < manifest->native_lib_count - 1) ? "," : "");
    }

    fprintf(file, "    ]\n");
    fprintf(file, "  }\n");
    fprintf(file, "}\n");

    fclose(file);
    ASSETS_INFO_LOG("JSON manifest written: %s", manifest_path);
    return 0;
}

// Simple JSON parser for our manifest format
// Returns 0 on success, -1 on error
static int read_manifest_json(const char *install_dir, Manifest *manifest) {
    char manifest_path[1024];
    snprintf(manifest_path, sizeof(manifest_path), "%s/%s", install_dir, MANIFEST_FILE_JSON);

    FILE *file = fopen(manifest_path, "r");
    if (!file) {
        return -1; // Manifest doesn't exist
    }

    // Simple JSON parsing - look for key-value pairs
    char line[2048];
    int in_native_libs = 0;
    int lib_index = 0;

    while (fgets(line, sizeof(line), file)) {
        // Remove whitespace
        char *p = line;
        while (*p && (*p == ' ' || *p == '\t')) p++;

        // Parse version
        if (sscanf(p, "\"version\": \"%127[^\"]\"", manifest->version) == 1) {
            continue;
        }

        // Parse platform
        if (sscanf(p, "\"platform\": \"%63[^\"]\"", manifest->platform) == 1) {
            continue;
        }

        // Parse ruby stdlib zip CRC32
        if (sscanf(p, "\"crc32\": \"%8x\"", &manifest->ruby_stdlib_zip_crc32) == 1 && !in_native_libs) {
            // This is a crude parser - assumes first CRC32 is ruby_stdlib
            continue;
        }

        // Parse native libs directory
        if (sscanf(p, "\"directory\": \"%511[^\"]\"", manifest->native_libs_dir) == 1) {
            in_native_libs = 1;
            continue;
        }

        // Parse native libs count
        if (sscanf(p, "\"count\": %d", &manifest->native_lib_count) == 1) {
            continue;
        }

        // Parse native library entries
        if (in_native_libs && lib_index < MAX_NATIVE_LIBS) {
            if (sscanf(p, "\"name\": \"%63[^\"]\"", manifest->native_libs[lib_index].name) == 1) {
                continue;
            }
            if (sscanf(p, "\"relative_path\": \"%255[^\"]\"",
                      manifest->native_libs[lib_index].relative_path) == 1) {
                continue;
            }
            if (sscanf(p, "\"crc32\": \"%8x\"", &manifest->native_libs[lib_index].crc32) == 1) {
                continue;
            }
            if (sscanf(p, "\"size\": %zu", &manifest->native_libs[lib_index].size) == 1) {
                lib_index++;
                continue;
            }
        }

        // Parse sizes (simple approach - order dependent)
        if (!in_native_libs) {
            size_t size_val;
            if (sscanf(p, "\"size\": %zu", &size_val) == 1) {
                // Crude: assign based on order
                if (manifest->ruby_stdlib_zip_size == 0) {
                    manifest->ruby_stdlib_zip_size = size_val;
                } else if (manifest->ruby_stdlib_ext_zip_size == 0) {
                    manifest->ruby_stdlib_ext_zip_size = size_val;
                }
            }
        }
    }

    fclose(file);
    return 0;
}

// Write manifest file
static int write_manifest(const char *install_dir, const Manifest *manifest) {
    char manifest_path[1024];
    snprintf(manifest_path, sizeof(manifest_path), "%s/%s", install_dir, MANIFEST_FILE);

    FILE *file = fopen(manifest_path, "w");
    if (!file) {
        ASSETS_ERROR_LOG("Failed to create manifest file %s: %s", manifest_path, strerror(errno));
        return -1;
    }

    fprintf(file, "# Embedded Ruby VM Installation Manifest\n");
    fprintf(file, "# Auto-generated - do not edit manually\n");
    fprintf(file, "\n");
    fprintf(file, "version=%s\n", manifest->version);
    fprintf(file, "ruby_stdlib_zip_crc32=%08X\n", manifest->ruby_stdlib_zip_crc32);
    fprintf(file, "ruby_stdlib_ext_zip_crc32=%08X\n", manifest->ruby_stdlib_ext_zip_crc32);
    fprintf(file, "ruby_stdlib_zip_size=%zu\n", manifest->ruby_stdlib_zip_size);
    fprintf(file, "ruby_stdlib_ext_zip_size=%zu\n", manifest->ruby_stdlib_ext_zip_size);

    fclose(file);
    ASSETS_INFO_LOG("Manifest written: %s", manifest_path);
    return 0;
}

// Verify that extracted files exist and have correct sizes
static int verify_installation(const char *install_dir) {
    char file_path[1024];
    struct stat st;

    // Check that ruby directory exists (we extract zips, so just check directory)
    snprintf(file_path, sizeof(file_path), "%s/ruby", install_dir);
    if (stat(file_path, &st) != 0 || !S_ISDIR(st.st_mode)) {
        ASSETS_DEBUG_LOG("Verification failed: %s directory not found", file_path);
        return -1;
    }

    return 0;
}

// Extract a zip file from memory to a directory
static int extract_zip_from_memory(const char *zip_data, size_t zip_size, const char *extract_dir) {
    void *zip_handle = NULL;
    void *stream = NULL;
    int32_t err = MZ_OK;
    mz_zip_file *file_info = NULL;
    char extract_path[1024];
    FILE *output_file = NULL;
    void *buf = NULL;
    int32_t buf_size = 8192;
    int32_t bytes_read = 0;

    // Create memory stream
    stream = mz_stream_mem_create();
    if (!stream) {
        ASSETS_ERROR_LOG("Failed to create memory stream");
        return -1;
    }

    mz_stream_mem_set_buffer(stream, (void*)zip_data, zip_size);

    // Create zip reader
    zip_handle = mz_zip_reader_create();
    if (!zip_handle) {
        ASSETS_ERROR_LOG("Failed to create zip reader");
        goto cleanup;
    }

    // Open zip from memory stream
    err = mz_zip_reader_open(zip_handle, stream);
    if (err != MZ_OK) {
        ASSETS_ERROR_LOG("Failed to open zip from memory: %d", err);
        goto cleanup;
    }

    // Go to first entry
    err = mz_zip_reader_goto_first_entry(zip_handle);
    if (err != MZ_OK && err != MZ_END_OF_LIST) {
        ASSETS_ERROR_LOG("Failed to go to first zip entry: %d", err);
        goto cleanup;
    }

    buf = malloc(buf_size);
    if (!buf) {
        ASSETS_ERROR_LOG("Failed to allocate buffer");
        err = MZ_MEM_ERROR;
        goto cleanup;
    }

    // Extract all entries
    do {
        err = mz_zip_reader_entry_get_info(zip_handle, &file_info);
        if (err != MZ_OK) {
            ASSETS_ERROR_LOG("Failed to get zip entry info: %d", err);
            goto cleanup;
        }

        // Skip directories (check if filename ends with '/')
        if (file_info->filename[strlen(file_info->filename) - 1] == '/') {
            snprintf(extract_path, sizeof(extract_path), "%s/%s", extract_dir, file_info->filename);
            // Remove trailing slash
            extract_path[strlen(extract_path) - 1] = '\0';
            if (mkdir(extract_path, 0755) != 0 && errno != EEXIST) {
                ASSETS_ERROR_LOG("Failed to create directory %s: %s", extract_path, strerror(errno));
                // Continue with other files
            }
        } else {
            // Extract file
            snprintf(extract_path, sizeof(extract_path), "%s/%s", extract_dir, file_info->filename);

            // Create parent directories
            if (create_directories(extract_path) != 0) {
                ASSETS_ERROR_LOG("Failed to create parent directories for %s", extract_path);
                goto next_entry;
            }

            // Open entry for reading
            err = mz_zip_reader_entry_open(zip_handle);
            if (err != MZ_OK) {
                ASSETS_ERROR_LOG("Failed to open zip entry %s: %d", file_info->filename, err);
                goto next_entry;
            }

            // Open output file
            output_file = fopen(extract_path, "wb");
            if (!output_file) {
                ASSETS_ERROR_LOG("Failed to create file %s: %s", extract_path, strerror(errno));
                mz_zip_reader_entry_close(zip_handle);
                goto next_entry;
            }

            // Read and write file data
            do {
                bytes_read = mz_zip_reader_entry_read(zip_handle, buf, buf_size);
                if (bytes_read < 0) {
                    ASSETS_ERROR_LOG("Error reading from zip entry: %d", bytes_read);
                    break;
                }
                if (bytes_read > 0) {
                    if (fwrite(buf, 1, bytes_read, output_file) != (size_t)bytes_read) {
                        ASSETS_ERROR_LOG("Error writing to file %s: %s", extract_path, strerror(errno));
                        break;
                    }
                }
            } while (bytes_read > 0);

            fclose(output_file);
            output_file = NULL;

            mz_zip_reader_entry_close(zip_handle);

        }

next_entry:
        err = mz_zip_reader_goto_next_entry(zip_handle);
    } while (err == MZ_OK);

    if (err == MZ_END_OF_LIST) {
        err = MZ_OK; // Normal end of entries
    }

cleanup:
    if (buf) free(buf);
    if (zip_handle) {
        mz_zip_reader_close(zip_handle);
        mz_zip_reader_delete(&zip_handle);
    }
    mz_stream_mem_delete(&stream);

    return (err == MZ_OK) ? 0 : -1;
}

#ifdef HAS_EMBEDDED_NATIVE_LIBS

// Write binary data to a file
static int write_binary_file(const char *filename, const char *data, size_t size) {
    // Create parent directories
    if (create_directories(filename) != 0) {
        return -1;
    }

    FILE *file = fopen(filename, "wb");
    if (!file) {
        ASSETS_ERROR_LOG("Failed to create file %s: %s", filename, strerror(errno));
        return -1;
    }

    size_t written = fwrite(data, 1, size, file);
    fclose(file);

    if (written != size) {
        ASSETS_ERROR_LOG("Failed to write complete data to %s", filename);
        return -1;
    }

    ASSETS_DEBUG_LOG("Created: %s (%zu bytes)", filename, size);
    return 0;
}

// Structure mapping library names to their embedded data symbols
typedef struct {
    const char* name;
    const char* data_start;
    const char* data_end;
} EmbeddedNativeLib;

// Forward declaration
static void create_library_version_symlinks(const char* lib_dir);

// Extract a single native library from embedded data
static int extract_native_library(const char* lib_name,
                                   const char* lib_data_start,
                                   const char* lib_data_end,
                                   const char* output_dir,
                                   Manifest* manifest,
                                   int* lib_index) {
    char output_path[1024];
    snprintf(output_path, sizeof(output_path), "%s/%s", output_dir, lib_name);

    // Calculate size
    size_t lib_size = lib_data_end - lib_data_start;

    ASSETS_INFO_LOG("Extracting native library: %s (%zu bytes)", lib_name, lib_size);

    // Write library file
    if (write_binary_file(output_path, lib_data_start, lib_size) != 0) {
        ASSETS_ERROR_LOG("Failed to extract native library: %s", lib_name);
        return -1;
    }

    // Set executable permissions (755)
    chmod(output_path, 0755);

    // Add to manifest if we have space
    if (*lib_index < MAX_NATIVE_LIBS) {
        strncpy(manifest->native_libs[*lib_index].name, lib_name,
               sizeof(manifest->native_libs[*lib_index].name) - 1);
        manifest->native_libs[*lib_index].name[sizeof(manifest->native_libs[*lib_index].name) - 1] = '\0';

        strncpy(manifest->native_libs[*lib_index].relative_path, lib_name,
               sizeof(manifest->native_libs[*lib_index].relative_path) - 1);
        manifest->native_libs[*lib_index].relative_path[sizeof(manifest->native_libs[*lib_index].relative_path) - 1] = '\0';

        manifest->native_libs[*lib_index].crc32 = compute_crc32(lib_data_start, lib_size);
        manifest->native_libs[*lib_index].size = lib_size;

        (*lib_index)++;
    }

    return 0;
}

// Extract all embedded native libraries
static int extract_all_native_libraries(const char* install_dir, Manifest* manifest) {
    char native_libs_dir[1024];
    char native_libs_parent[1024];

    // Use the platform from manifest (already set by install_embedded_files)
    snprintf(native_libs_dir, sizeof(native_libs_dir),
             "%s/native-libs/%s", install_dir, manifest->platform);

    ASSETS_INFO_LOG("Extracting native libraries to: %s", native_libs_dir);

    // Create parent native-libs directory first
    snprintf(native_libs_parent, sizeof(native_libs_parent), "%s/native-libs", install_dir);
    if (mkdir(native_libs_parent, 0755) != 0 && errno != EEXIST) {
        ASSETS_ERROR_LOG("Failed to create parent native-libs directory: %s", strerror(errno));
        return -1;
    }

    // Create platform-specific native libs directory
    if (mkdir(native_libs_dir, 0755) != 0 && errno != EEXIST) {
        ASSETS_ERROR_LOG("Failed to create native libs directory: %s", strerror(errno));
        return -1;
    }

    int lib_count = 0;

    // Extract each embedded library
    // Note: Only extract if the symbol exists (some builds may not have all libs)
    #define EXTRACT_LIB(name, start, end) \
        if (&start != NULL && &end != NULL) { \
            extract_native_library(name, start, end, native_libs_dir, manifest, &lib_count); \
        }

    EXTRACT_LIB("libruby.so", _binary_libruby_so_start, _binary_libruby_so_end);
    EXTRACT_LIB("libssl.so", _binary_libssl_so_start, _binary_libssl_so_end);
    EXTRACT_LIB("libcrypto.so", _binary_libcrypto_so_start, _binary_libcrypto_so_end);
    EXTRACT_LIB("libreadline.so", _binary_libreadline_so_start, _binary_libreadline_so_end);
    EXTRACT_LIB("libhistory.so", _binary_libhistory_so_start, _binary_libhistory_so_end);
    EXTRACT_LIB("libgdbm.so", _binary_libgdbm_so_start, _binary_libgdbm_so_end);
    EXTRACT_LIB("libgdbm_compat.so", _binary_libgdbm_compat_so_start, _binary_libgdbm_compat_so_end);
    EXTRACT_LIB("libncurses.so", _binary_libncurses_so_start, _binary_libncurses_so_end);
    EXTRACT_LIB("libpanel.so", _binary_libpanel_so_start, _binary_libpanel_so_end);
    EXTRACT_LIB("libmenu.so", _binary_libmenu_so_start, _binary_libmenu_so_end);
    EXTRACT_LIB("libform.so", _binary_libform_so_start, _binary_libform_so_end);
    EXTRACT_LIB("libcurses.so", _binary_libcurses_so_start, _binary_libcurses_so_end);

    #undef EXTRACT_LIB

    manifest->native_lib_count = lib_count;

    ASSETS_INFO_LOG("Extracted %d native libraries", lib_count);
    
    // Create version-specific symlinks for libraries
    // This allows binaries linked against libruby.so.3.1 to find libruby.so
    create_library_version_symlinks(native_libs_dir);
    
    return 0;
}

// Helper function to create version symlinks for shared libraries
// E.g., creates libruby.so.3.1 -> libruby.so, libssl.so.3 -> libssl.so
static void create_library_version_symlinks(const char* lib_dir) {
    // Common version suffix patterns for the libraries we embed
    // Format: {base_name, version_suffix}
    struct {
        const char* base;
        const char* versions[3];  // Try multiple common versions
    } lib_versions[] = {
        {"libruby.so", {"3.1", "3.1.0", NULL}},
        {"libssl.so", {"3", "1.1", NULL}},
        {"libcrypto.so", {"3", "1.1", NULL}},
        {"libreadline.so", {"8", "7", NULL}},
        {"libhistory.so", {"8", "7", NULL}},
        {"libgdbm.so", {"6", "5", NULL}},
        {"libgdbm_compat.so", {"4", NULL, NULL}},
        {"libncurses.so", {"6", "5", NULL}},
        {"libpanel.so", {"6", "5", NULL}},
        {"libmenu.so", {"6", "5", NULL}},
        {"libform.so", {"6", "5", NULL}},
        {"libcurses.so", {"6", "5", NULL}},
        {NULL, {NULL, NULL, NULL}}
    };
    
    ASSETS_INFO_LOG("Creating version symlinks in: %s", lib_dir);
    
    for (int i = 0; lib_versions[i].base != NULL; i++) {
        const char* base_name = lib_versions[i].base;
        char target_path[1024];
        snprintf(target_path, sizeof(target_path), "%s/%s", lib_dir, base_name);
        
        // Check if the base library exists
        if (access(target_path, F_OK) != 0) {
            continue;  // Skip if library doesn't exist
        }
        
        // Create symlinks for each version suffix
        for (int v = 0; v < 3 && lib_versions[i].versions[v] != NULL; v++) {
            const char* version = lib_versions[i].versions[v];
            char symlink_name[1024];
            snprintf(symlink_name, sizeof(symlink_name), "%s/%s.%s", 
                    lib_dir, base_name, version);
            
            // Remove existing symlink if present
            unlink(symlink_name);
            
            // Create symlink: libruby.so.3.1 -> libruby.so
            if (symlink(base_name, symlink_name) == 0) {
                ASSETS_INFO_LOG("  Created symlink: %s.%s -> %s", base_name, version, base_name);
            } else {
                ASSETS_DEBUG_LOG("  Failed to create symlink %s.%s: %s", 
                               base_name, version, strerror(errno));
            }
        }
    }
}
#endif // HAS_EMBEDDED_NATIVE_LIBS

// Main installation function
int install_embedded_files(const char *install_dir, AssetsError* error) {
    int result = 0;

    if (!install_dir) {
        assets_error_set(error, ASSETS_ERROR_INVALID_PARAM, NULL,
                        "Install directory cannot be NULL");
        return ASSETS_ERROR_INVALID_PARAM;
    }

    ASSETS_INFO_LOG("Installing embedded files to: %s", install_dir);

    // Create base installation directory
    if (mkdir(install_dir, 0755) != 0 && errno != EEXIST) {
        assets_error_set_errno(error, ASSETS_ERROR_MKDIR, install_dir,
                              "Failed to create install directory");
        return ASSETS_ERROR_MKDIR;
    }

    // Extract Ruby standard library ZIP
    ASSETS_INFO_LOG("Extracting Ruby standard library...");
    size_t ruby_stdlib_size = _binary_ruby_stdlib_zip_end - _binary_ruby_stdlib_zip_start;
    if (mkdir(install_dir, 0755) != 0 && errno != EEXIST) {
        assets_error_set_errno(error, ASSETS_ERROR_MKDIR, install_dir,
                              "Failed to create ruby-stdlib directory");
        result = ASSETS_ERROR_MKDIR;
    } else {
        if (extract_zip_from_memory(_binary_ruby_stdlib_zip_start, ruby_stdlib_size, install_dir) != 0) {
            assets_error_set(error, ASSETS_ERROR_ZIP_EXTRACT, "ruby-stdlib.zip",
                           "Failed to extract Ruby standard library");
            result = ASSETS_ERROR_ZIP_EXTRACT;
        }
    }

    ASSETS_INFO_LOG("Extracting Ruby standard library platform specifics...");
    size_t ruby_stdlib_ext_size = _binary_ruby_stdlib_ext_zip_end - _binary_ruby_stdlib_ext_zip_start;
    if (extract_zip_from_memory(_binary_ruby_stdlib_ext_zip_start, ruby_stdlib_ext_size, install_dir) != 0) {
        assets_error_set(error, ASSETS_ERROR_ZIP_EXTRACT, "ruby-stdlib-ext.zip",
                       "Failed to extract Ruby standard library extensions");
        result = ASSETS_ERROR_ZIP_EXTRACT;
    }

    if (result == 0) {
        // Write manifest file after successful installation
        ASSETS_INFO_LOG("Writing installation manifest...");

        Manifest manifest = {0};

        // Compute CRC32 checksums of embedded data
        manifest.ruby_stdlib_zip_crc32 = compute_crc32(_binary_ruby_stdlib_zip_start, ruby_stdlib_size);
        manifest.ruby_stdlib_ext_zip_crc32 = compute_crc32(_binary_ruby_stdlib_ext_zip_start, ruby_stdlib_ext_size);

        manifest.ruby_stdlib_zip_size = ruby_stdlib_size;
        manifest.ruby_stdlib_ext_zip_size = ruby_stdlib_ext_size;

        // Platform detection
#if defined(__x86_64__) || defined(_M_X64)
    #if defined(__linux__)
        snprintf(manifest.platform, sizeof(manifest.platform), "x86_64-linux-linux");
    #elif defined(__ANDROID__)
        snprintf(manifest.platform, sizeof(manifest.platform), "x86_64-linux-android");
    #elif defined(__APPLE__)
        snprintf(manifest.platform, sizeof(manifest.platform), "x86_64-darwin");
    #endif
#elif defined(__aarch64__) || defined(_M_ARM64)
    #if defined(__linux__)
        snprintf(manifest.platform, sizeof(manifest.platform), "aarch64-linux-linux");
    #elif defined(__ANDROID__)
        snprintf(manifest.platform, sizeof(manifest.platform), "aarch64-linux-android");
    #elif defined(__APPLE__)
        snprintf(manifest.platform, sizeof(manifest.platform), "aarch64-darwin");
    #endif
#else
        snprintf(manifest.platform, sizeof(manifest.platform), "unknown");
#endif

        // Set up native libs directory
        snprintf(manifest.native_libs_dir, sizeof(manifest.native_libs_dir), "native-libs/%s", manifest.platform);
        manifest.native_lib_count = 0;

        int native_libs_result = 0;
#ifdef HAS_EMBEDDED_NATIVE_LIBS
        // Extract embedded native libraries (Phase 2)
        ASSETS_INFO_LOG("Extracting embedded native libraries...");
        native_libs_result = extract_all_native_libraries(install_dir, &manifest);
        if (native_libs_result != 0) {
            ASSETS_ERROR_LOG("Failed to extract native libraries");
            // Continue anyway - Ruby can still work without native libs
        }
#endif

        // Generate auto-version from CRC32 hashes
        generate_auto_version(manifest.version, sizeof(manifest.version),
                              manifest.ruby_stdlib_zip_crc32,
                              manifest.ruby_stdlib_ext_zip_crc32);

        // Write both INI format (backward compat) and JSON format (new)
        if (write_manifest(install_dir, &manifest) != 0) {
            ASSETS_ERROR_LOG("Warning: Failed to write INI manifest file");
            // Don't fail installation due to manifest write failure
        }

        if (write_manifest_json(install_dir, &manifest) != 0) {
            ASSETS_ERROR_LOG("Warning: Failed to write JSON manifest file");
            // Don't fail installation due to manifest write failure
        }

        if (native_libs_result == 0) {
            ASSETS_INFO_LOG("Installation completed successfully!");
        } else {
            ASSETS_INFO_LOG("Installation completed with warnings (native libraries failed to extract)");
        }
        ASSETS_INFO_LOG("Version: %s (Platform: %s)", manifest.version, manifest.platform);
    } else {
        ASSETS_ERROR_LOG("Installation completed with errors");
    }

    return result;
}

// Convenience function to get default install directory (can be customized)
const char* get_default_install_dir(void) {
    static char install_dir[1024];
    const char *cache_dir = getenv("XDG_CACHE_HOME");

    if (!cache_dir) {
        const char *home = getenv("HOME");
        if (home) {
            snprintf(install_dir, sizeof(install_dir), "%s/.cache/your_app", home);
        } else {
            // Fallback for Android or systems without HOME
            snprintf(install_dir, sizeof(install_dir), "/tmp/your_app_install");
        }
    } else {
        snprintf(install_dir, sizeof(install_dir), "%s/your_app", cache_dir);
    }

    return install_dir;
}

// Function to check if installation is needed (files exist and are valid)
int installation_needed(const char *install_dir, AssetsError* error) {
    Manifest current_manifest = {0};
    Manifest embedded_manifest = {0};

    if (!install_dir) {
        assets_error_set(error, ASSETS_ERROR_INVALID_PARAM, NULL,
                        "Install directory cannot be NULL");
        return ASSETS_ERROR_INVALID_PARAM;
    }

    // Build expected manifest from embedded data
    size_t ruby_stdlib_size = _binary_ruby_stdlib_zip_end - _binary_ruby_stdlib_zip_start;
    size_t ruby_stdlib_ext_size = _binary_ruby_stdlib_ext_zip_end - _binary_ruby_stdlib_ext_zip_start;

    ASSETS_DEBUG_LOG("Computing CRC32 checksums of embedded files...");
    embedded_manifest.ruby_stdlib_zip_crc32 = compute_crc32(_binary_ruby_stdlib_zip_start, ruby_stdlib_size);
    embedded_manifest.ruby_stdlib_ext_zip_crc32 = compute_crc32(_binary_ruby_stdlib_ext_zip_start, ruby_stdlib_ext_size);

    embedded_manifest.ruby_stdlib_zip_size = ruby_stdlib_size;
    embedded_manifest.ruby_stdlib_ext_zip_size = ruby_stdlib_ext_size;

    // Generate auto-version from CRC32 hashes
    generate_auto_version(embedded_manifest.version, sizeof(embedded_manifest.version),
                          embedded_manifest.ruby_stdlib_zip_crc32,
                          embedded_manifest.ruby_stdlib_ext_zip_crc32);

    ASSETS_INFO_LOG("Embedded data version: %s", embedded_manifest.version);

    // Try to read existing manifest
    if (read_manifest(install_dir, &current_manifest) != 0) {
        ASSETS_INFO_LOG("No manifest found - installation needed");
        return 1; // No manifest = need installation
    }

    ASSETS_INFO_LOG("Installed version: %s", current_manifest.version);

    // Quick version check (fast path - avoids filesystem verification)
    if (strcmp(current_manifest.version, embedded_manifest.version) != 0) {
        ASSETS_INFO_LOG("Version mismatch - installation needed");
        ASSETS_DEBUG_LOG("  Expected: %s", embedded_manifest.version);
        ASSETS_DEBUG_LOG("  Found:    %s", current_manifest.version);
        return 1;
    }

    // Version matches - verify CRC32 values match (belt and suspenders)
    if (current_manifest.ruby_stdlib_zip_crc32 != embedded_manifest.ruby_stdlib_zip_crc32 ||
        current_manifest.ruby_stdlib_ext_zip_crc32 != embedded_manifest.ruby_stdlib_ext_zip_crc32) {
        ASSETS_INFO_LOG("CRC32 mismatch detected - installation needed");
        return 1;
    }

    // Verify extracted files still exist and have correct sizes
    ASSETS_DEBUG_LOG("Verifying installation integrity...");
    if (verify_installation(install_dir) != 0) {
        ASSETS_INFO_LOG("Installation verification failed - reinstallation needed");
        return 1;
    }

    ASSETS_INFO_LOG("Installation is up-to-date - skipping extraction");
    return 0; // Installation not needed
}

// ============================================================================
// Public API Functions (work with or without HAS_EMBEDDED_DATA)
// ============================================================================

/**
 * Get the complete asset layout after installation.
 * This is the single source of truth for asset paths.
 */
AssetsLayout* assets_get_layout(const char* install_dir, AssetsError* error) {
    if (!install_dir) {
        assets_error_set(error, ASSETS_ERROR_INVALID_PARAM, NULL,
                        "Install directory cannot be NULL");
        return NULL;
    }

    // Try reading JSON manifest first (new format)
    Manifest manifest = {0};
    int json_result = read_manifest_json(install_dir, &manifest);

    // Fallback to INI format if JSON not found
    if (json_result != 0) {
        ASSETS_DEBUG_LOG("JSON manifest not found, trying INI format...");
        if (read_manifest(install_dir, &manifest) != 0) {
            assets_error_set(error, ASSETS_ERROR_FILE_READ, install_dir,
                           "Cannot read manifest file (tried both JSON and INI formats)");
            return NULL;
        }
    }

    // Allocate and populate layout structure
    AssetsLayout* layout = (AssetsLayout*)calloc(1, sizeof(AssetsLayout));
    if (!layout) {
        assets_error_set(error, ASSETS_ERROR_MEMORY, NULL,
                        "Failed to allocate memory for AssetsLayout");
        return NULL;
    }

    // Populate paths
    snprintf(layout->ruby_stdlib_path, sizeof(layout->ruby_stdlib_path),
             "%s/ruby/%s", install_dir, RUBY_VERSION);

    snprintf(layout->ruby_stdlib_ext_path, sizeof(layout->ruby_stdlib_ext_path),
             "%s/ruby/%s", install_dir, RUBY_VERSION);

    // Build native libs directory path (ensuring no truncation)
    int needed = snprintf(layout->native_libs_dir, sizeof(layout->native_libs_dir),
                          "%s/%s", install_dir, manifest.native_libs_dir);
    if (needed >= (int)sizeof(layout->native_libs_dir)) {
        ASSETS_ERROR_LOG("Native libs directory path too long");
    }

    // Copy platform and version with null termination
    strncpy(layout->platform, manifest.platform, sizeof(layout->platform) - 1);
    layout->platform[sizeof(layout->platform) - 1] = '\0';

    strncpy(layout->version, manifest.version, sizeof(layout->version) - 1);
    layout->version[sizeof(layout->version) - 1] = '\0';

    // Copy native library information
    layout->native_lib_count = manifest.native_lib_count;
    for (int i = 0; i < manifest.native_lib_count && i < MAX_NATIVE_LIBS; i++) {
        layout->native_libs[i] = manifest.native_libs[i];
    }

    ASSETS_INFO_LOG("Asset layout loaded: version=%s, platform=%s, native_libs=%d",
                   layout->version, layout->platform, layout->native_lib_count);

    return layout;
}

/**
 * Free an AssetsLayout structure.
 */
void assets_free_layout(AssetsLayout* layout) {
    if (layout) {
        free(layout);
    }
}

/**
 * Validate that all assets in the layout exist and match their checksums.
 */
int assets_validate_layout(const AssetsLayout* layout, int verify_checksums, AssetsError* error) {
    if (!layout) {
        assets_error_set(error, ASSETS_ERROR_INVALID_PARAM, NULL,
                        "Layout cannot be NULL");
        return ASSETS_ERROR_INVALID_PARAM;
    }

    struct stat st;

    // Check Ruby stdlib directory
    if (stat(layout->ruby_stdlib_path, &st) != 0 || !S_ISDIR(st.st_mode)) {
        assets_error_set_errno(error, ASSETS_ERROR_FILE_READ, layout->ruby_stdlib_path,
                              "Ruby stdlib directory not found");
        return ASSETS_ERROR_FILE_READ;
    }

    // Check native libs directory (if populated)
    if (layout->native_lib_count > 0) {
        if (stat(layout->native_libs_dir, &st) != 0 || !S_ISDIR(st.st_mode)) {
            assets_error_set_errno(error, ASSETS_ERROR_FILE_READ, layout->native_libs_dir,
                                  "Native libraries directory not found");
            return ASSETS_ERROR_FILE_READ;
        }

        // Verify each native library exists
        for (int i = 0; i < layout->native_lib_count; i++) {
            char lib_path[1024];
            snprintf(lib_path, sizeof(lib_path), "%s/%s",
                    layout->native_libs_dir, layout->native_libs[i].relative_path);

            if (stat(lib_path, &st) != 0) {
                assets_error_set_errno(error, ASSETS_ERROR_FILE_READ, lib_path,
                                      "Native library file not found");
                return ASSETS_ERROR_FILE_READ;
            }

            // Verify size
            if ((size_t)st.st_size != layout->native_libs[i].size) {
                char err_msg[256];
                snprintf(err_msg, sizeof(err_msg),
                        "Native library size mismatch (expected %zu, got %lld)",
                        layout->native_libs[i].size, (long long)st.st_size);
                assets_error_set(error, ASSETS_ERROR_SIZE_MISMATCH, lib_path, err_msg);
                return ASSETS_ERROR_SIZE_MISMATCH;
            }

            // Optionally verify CRC32 (slower)
            if (verify_checksums) {
                FILE* fp = fopen(lib_path, "rb");
                if (!fp) {
                    assets_error_set_errno(error, ASSETS_ERROR_FILE_READ, lib_path,
                                          "Cannot open library for checksum verification");
                    return ASSETS_ERROR_FILE_READ;
                }

                // Read file and compute CRC32
                fseek(fp, 0, SEEK_END);
                long file_size = ftell(fp);
                fseek(fp, 0, SEEK_SET);

                char* buffer = (char*)malloc(file_size);
                if (!buffer) {
                    fclose(fp);
                    assets_error_set(error, ASSETS_ERROR_MEMORY, NULL,
                                   "Failed to allocate memory for checksum verification");
                    return ASSETS_ERROR_MEMORY;
                }

                size_t bytes_read = fread(buffer, 1, file_size, fp);
                fclose(fp);

                if (bytes_read != (size_t)file_size) {
                    free(buffer);
                    assets_error_set(error, ASSETS_ERROR_FILE_READ, lib_path,
                                   "Failed to read complete file for checksum verification");
                    return ASSETS_ERROR_FILE_READ;
                }

                uint32_t computed_crc = compute_crc32(buffer, file_size);
                free(buffer);

                if (computed_crc != layout->native_libs[i].crc32) {
                    char err_msg[256];
                    snprintf(err_msg, sizeof(err_msg),
                            "Native library CRC32 mismatch (expected %08X, got %08X)",
                            layout->native_libs[i].crc32, computed_crc);
                    assets_error_set(error, ASSETS_ERROR_CRC_MISMATCH, lib_path, err_msg);
                    return ASSETS_ERROR_CRC_MISMATCH;
                }
            }
        }
    }

    ASSETS_INFO_LOG("Asset layout validation successful");
    return ASSETS_OK;
}

/**
 * Register external native libraries in the manifest.
 * This is used when libs are NOT embedded - the "hybrid approach".
 */
int assets_register_native_libs(const char* install_dir,
                                 const char* external_lib_dir,
                                 const char* platform,
                                 AssetsError* error) {
    if (!install_dir || !external_lib_dir || !platform) {
        assets_error_set(error, ASSETS_ERROR_INVALID_PARAM, NULL,
                        "Install directory, external lib directory, and platform cannot be NULL");
        return ASSETS_ERROR_INVALID_PARAM;
    }

    // Read existing manifest
    Manifest manifest = {0};
    if (read_manifest_json(install_dir, &manifest) != 0) {
        // Try INI format
        if (read_manifest(install_dir, &manifest) != 0) {
            assets_error_set(error, ASSETS_ERROR_FILE_READ, install_dir,
                           "Cannot read existing manifest");
            return ASSETS_ERROR_FILE_READ;
        }
    }

    // Scan external lib directory for .so files
    // For now, we'll use a simple implementation that lists known libraries
    // A more robust implementation would use opendir/readdir

    const char* known_libs[] = {
        "libruby.so", "libssl.so", "libcrypto.so", "libreadline.so",
        "libhistory.so", "libgdbm.so", "libncurses.so", "libpanel.so",
        "libmenu.so", "libform.so", "libcurses.so", "libgdbm_compat.so"
    };

    int num_known_libs = sizeof(known_libs) / sizeof(known_libs[0]);
    int lib_count = 0;

    for (int i = 0; i < num_known_libs && lib_count < MAX_NATIVE_LIBS; i++) {
        char lib_path[1024];
        snprintf(lib_path, sizeof(lib_path), "%s/%s", external_lib_dir, known_libs[i]);

        struct stat st;
        if (stat(lib_path, &st) == 0 && S_ISREG(st.st_mode)) {
            // Library exists - read and compute CRC32
            FILE* fp = fopen(lib_path, "rb");
            if (!fp) continue;

            fseek(fp, 0, SEEK_END);
            long file_size = ftell(fp);
            fseek(fp, 0, SEEK_SET);

            char* buffer = (char*)malloc(file_size);
            if (!buffer) {
                fclose(fp);
                continue;
            }

            size_t bytes_read = fread(buffer, 1, file_size, fp);
            fclose(fp);

            if (bytes_read != (size_t)file_size) {
                free(buffer);
                continue;  // Skip this library if we can't read it
            }

            uint32_t crc = compute_crc32(buffer, file_size);
            free(buffer);

            // Add to manifest
            strncpy(manifest.native_libs[lib_count].name, known_libs[i],
                   sizeof(manifest.native_libs[lib_count].name) - 1);
            strncpy(manifest.native_libs[lib_count].relative_path, known_libs[i],
                   sizeof(manifest.native_libs[lib_count].relative_path) - 1);
            manifest.native_libs[lib_count].crc32 = crc;
            manifest.native_libs[lib_count].size = file_size;

            lib_count++;
        }
    }

    // Update manifest
    manifest.native_lib_count = lib_count;
    strncpy(manifest.platform, platform, sizeof(manifest.platform) - 1);
    snprintf(manifest.native_libs_dir, sizeof(manifest.native_libs_dir),
             "native-libs/%s", platform);

    // Write updated manifest
    if (write_manifest_json(install_dir, &manifest) != 0) {
        assets_error_set(error, ASSETS_ERROR_FILE_WRITE, install_dir,
                        "Failed to write updated manifest");
        return ASSETS_ERROR_FILE_WRITE;
    }

    // Also write INI format for backward compat
    write_manifest(install_dir, &manifest);

    ASSETS_INFO_LOG("Registered %d native libraries in manifest", lib_count);
    return ASSETS_OK;
}

/**
 * Bootstrap the Ruby runtime - high-level convenience function.
 *
 * This performs the complete initialization sequence:
 *   1. Check if extraction is needed
 *   2. Extract assets if needed
 *   3. Get asset layout
 *   4. Load native libraries in dependency order
 */
AssetsLayout* assets_bootstrap(const char* install_dir, AssetsError* error) {
    if (!install_dir) {
        assets_error_set(error, ASSETS_ERROR_INVALID_PARAM, NULL,
                        "Install directory cannot be NULL");
        return NULL;
    }

    AssetsError local_error = {0};
    AssetsLayout* layout = NULL;

    // Step 1: Check if installation is needed
    int needs_install = installation_needed(install_dir, &local_error);
    if (needs_install < 0) {
        // Error occurred
        if (error) {
            *error = local_error;
        }
        return NULL;
    }

    // Step 2: Extract assets if needed
    if (needs_install == 1) {
        assets_error_init(&local_error);
        int install_result = install_embedded_files(install_dir, &local_error);
        if (install_result != ASSETS_OK) {
            if (error) {
                *error = local_error;
            }
            return NULL;
        }
    }

    // Step 3: Get asset layout
    assets_error_init(&local_error);
    layout = assets_get_layout(install_dir, &local_error);
    if (!layout) {
        if (error) {
            *error = local_error;
        }
        return NULL;
    }

    // NOTE: We intentionally do NOT load the native libraries here
    // Loading should be done by the caller in the correct context
    // This avoids issues with Ruby's initialization code running prematurely

    ASSETS_INFO_LOG("Bootstrap complete - extracted files, returning layout");
#ifndef HAS_EMBEDDED_NATIVE_LIBS
    ASSETS_INFO_LOG("No native libraries have been embedded");
#else    
    ASSETS_INFO_LOG("Native libraries available at: %s", layout->native_libs_dir);
#endif
    return layout;
}

#else // !HAS_EMBEDDED_DATA

int install_embedded_files(const char *install_dir, AssetsError* error) {
    (void)install_dir; // Unused parameter
    assets_error_set(error, ASSETS_ERROR_NO_EMBEDDED_DATA, NULL,
                    "No embedded data available. Library was compiled without HAS_EMBEDDED_DATA");
    return ASSETS_ERROR_NO_EMBEDDED_DATA;
}

const char* get_default_install_dir(void) {
    return NULL;
}

int installation_needed(const char *install_dir, AssetsError* error) {
    (void)install_dir; // Unused parameter
    assets_error_set(error, ASSETS_ERROR_NO_EMBEDDED_DATA, NULL,
                    "No embedded data available. Library was compiled without HAS_EMBEDDED_DATA");
    return ASSETS_ERROR_NO_EMBEDDED_DATA;
}

AssetsLayout* assets_bootstrap(const char* install_dir, AssetsError* error) {
    (void)install_dir; // Unused parameter
    assets_error_set(error, ASSETS_ERROR_NO_EMBEDDED_DATA, NULL,
                    "No embedded data available. Library was compiled without HAS_EMBEDDED_DATA");
    return NULL;
}

#endif // HAS_EMBEDDED_DATA
