
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdarg.h>
#include <dirent.h>
#include <unistd.h>
// TODO: add a way to enable/disable this via CMake
#ifdef RUBY_REDIRECT_SIGNALS
#include <signal.h>
#endif
#include <sys/stat.h>
#include <errno.h>

#include "embedded-ruby-vm/constants.h"
#include "embedded-ruby-vm/exec-main-vm.h"
#include "embedded-ruby-vm/ruby-vm.h"
#include "embedded-ruby-vm/debug.h"
#include "embedded-ruby-vm/ruby-script.h"
#include "embedded-ruby-vm/ruby-custom-ext.h"
#include "embedded-ruby-vm/embedded_scripts.h"
#include "embedded-ruby-vm/logging.h"

#include "ruby/config.h"
#include "ruby/version.h"

// Global callback for custom extension initialization
// This allows external projects to register their own Ruby extensions
// that will be statically resolved (via require statements)
static RubyCustomExtInit g_custom_ext_init = NULL;

void ruby_set_custom_ext_init(RubyCustomExtInit init_func) {
    g_custom_ext_init = init_func;
}


static void SetupRubyEnv(const char* baseDirectory, const char* extraLoadPath)
{
#define RUBY_BUFFER_PATH_SIZE (256)
#define RUBY_NUM_PATH_IN_RUBYLIB_ENV_VAR (3)

#ifndef NDEBUG
    char mess[1024];
#endif
    char rubyVersion[64];
    snprintf(rubyVersion, sizeof(rubyVersion), "%d.%d.%d", RUBY_API_VERSION_MAJOR, RUBY_API_VERSION_MINOR, RUBY_API_VERSION_TEENY);

    const size_t baseDirectorySize = strlen(baseDirectory);
    const size_t maxRubyDirBufferSize = RUBY_NUM_PATH_IN_RUBYLIB_ENV_VAR *
            ((baseDirectorySize * sizeof(char) + sizeof(char)) +
            (strlen(rubyVersion) * sizeof(char)) +
            RUBY_BUFFER_PATH_SIZE);

    char* rubyBufferDir = (char*) malloc(maxRubyDirBufferSize);
    snprintf(rubyBufferDir, maxRubyDirBufferSize, "%s/ruby/gems/%s/", baseDirectory, rubyVersion);
    setenv("GEM_HOME", rubyBufferDir, 1);
    setenv("GEM_PATH", rubyBufferDir, 1);
    strncat(rubyBufferDir, "specifications/", maxRubyDirBufferSize);
    setenv("GEM_SPEC_CACHE", rubyBufferDir, 1);

    snprintf(rubyBufferDir, maxRubyDirBufferSize, "%s:%s/ruby/%s/:%s/ruby/%s/"RUBY_PLATFORM"/:%s", baseDirectory, baseDirectory, rubyVersion, baseDirectory, rubyVersion, extraLoadPath);
    setenv("RUBYLIB", rubyBufferDir, 1);

    // Set NDEBUG environment variable for Ruby VM logging control
#ifdef NDEBUG
    setenv("NDEBUG", "1", 1);  // Release build
#else
    setenv("NDEBUG", "0", 1);  // Debug build
#endif

#ifndef NDEBUG
    snprintf(mess, sizeof(mess), "Ruby VM env. variables :\nGEM_HOME = '%s'\nGEM_PATH = '%s'\nGEM_SPEC_CACHE = '%s'\nRUBYLIB = '%s'",
             getenv("GEM_HOME"), getenv("GEM_PATH"), getenv("GEM_SPEC_CACHE"), getenv("RUBYLIB"));
    printf("%s\n", mess);
#endif

    free(rubyBufferDir);
}

#pragma GCC diagnostic push
#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wunused-parameter"
#else
#ifdef __clang__
#pragma clang diagnostic ignored "-Wdefault-const-init-field-unsafe"
#pragma clang diagnostic ignored "-Wunused-parameter"
#endif
#endif
#include "ruby/ruby.h"
#pragma GCC diagnostic pop

// Forward declaration for static extension initialization
// This function is generated by Ruby's build system when using --with-static-linked-ext
// It calls all the Init_* functions (Init_monitor, Init_readline, etc.)
extern void Init_ext(void);

// Pull the message out of $! (rb_errinfo) and report it on stderr, then
// clear the error so subsequent Ruby calls aren't confused. Use this after
// any rb_eval_string_protect call that came back with a non-zero state.
// `what` is a short label describing what was being attempted; it's
// prepended to the message in the "[Ruby VM] Failed to <what>: ..." line.
static void report_ruby_eval_error(const char* what) {
    VALUE err = rb_errinfo();
    const char* msg = "<no message>";
    if (!NIL_P(err)) {
        VALUE m = rb_funcall(err, rb_intern("message"), 0);
        if (RB_TYPE_P(m, T_STRING)) msg = StringValueCStr(m);
    }
    fprintf(stderr, "[Ruby VM] Failed to %s: %s\n", what, msg);
    rb_set_errinfo(Qnil);
}

// Evaluate an embedded script (looked up by name) safely.
//
// The scripts are stored as objcopy-embedded byte spans bracketed by
// _binary_<name>_rb_{start,end} symbols. They are NOT null-terminated —
// objcopy emits raw bytes. Calling `rb_eval_string(start)` would read past
// `_end` into whatever .data section follows, which produced silent
// duplicate-constant warnings (and worse, double-evaluation of code) once
// a second embedded script landed adjacent to safe_runner.rb's bytes.
//
// We work around it by copying the bytes into a heap buffer with an
// explicit trailing NUL, evaluating that, then freeing. `state_out` is
// optional; when non-NULL we use rb_eval_string_protect, otherwise the
// plain rb_eval_string. Returns -1 if the script name is unknown or
// allocation failed, 0 otherwise (Ruby errors are surfaced via *state_out).
static int eval_embedded_script(const char* script_name, int* state_out) {
    const char* src = embedded_script_get_content(script_name);
    size_t      len = embedded_script_get_size(script_name);
    if (!src || len == 0) {
        return -1;
    }
    char* buf = malloc(len + 1);
    if (!buf) {
        return -1;
    }
    memcpy(buf, src, len);
    buf[len] = '\0';
    if (state_out) {
        rb_eval_string_protect(buf, state_out);
    } else {
        rb_eval_string(buf);
    }
    free(buf);
    return 0;
}

// Build argv with variable number of arguments
static char** build_ruby_argv_va(int* argc_out,
                                 const char* script_content,
                                 int from_filename,
                                 int extra_args_count,
                                 ...)
{
    va_list args;
    va_start(args, extra_args_count);

    int base_argc = from_filename == 0 ? 3 : 2;
    int argc = base_argc + extra_args_count;

    char **argv = (char**) malloc(sizeof(char*) * argc);
    int idx = 0;

    // Base arguments
    argv[idx++] = strdup("ruby");

    if (from_filename == 0) {
        argv[idx++] = strdup("-e");
    }

    argv[idx++] = strdup(script_content);

    // Extra arguments
    for (int i = 0; i < extra_args_count; i++) {
        const char* arg = va_arg(args, const char*);
        argv[idx++] = strdup(arg);
    }

    va_end(args);

    *argc_out = argc;
    return argv;
}

static void free_ruby_argv(char** argv, int argc) {
    for (int i = 0; i < argc; i++) {
        free(argv[i]);
    }
    free(argv);
}

#ifdef RUBY_REDIRECT_SIGNALS
// Store original signal handlers
static struct sigaction original_sigpipe;
static struct sigaction original_sigchld;
static struct sigaction original_sigsegv;

/**
 * Save original Android signal handlers before Ruby overwrites them
 */
static void SaveOriginalSignalHandlers(void) {
    sigaction(SIGPIPE, NULL, &original_sigpipe);
    sigaction(SIGCHLD, NULL, &original_sigchld);
    sigaction(SIGSEGV, NULL, &original_sigsegv);
}

/**
 * Restore critical signal handlers after Ruby initialization
 */
static void RestoreCriticalSignalHandlers(void) {
    // Restore SIGPIPE - critical for Android's Binder IPC
    if (sigaction(SIGPIPE, &original_sigpipe, NULL) != 0) {
        fprintf(stderr, "Failed to restore SIGPIPE handler\n");
    }

    // For SIGCHLD, we need a compromise - chain handlers
    // (Ruby needs it for Process.wait, Android needs it for Runtime.exec)
}

/**
 * Custom SIGCHLD handler that chains to both Ruby and Android
 */
static void ChainedSigchldHandler(int sig, siginfo_t *info, void *context) {
    // Call original Android handler first
    if (original_sigchld.sa_flags & SA_SIGINFO) {
        if (original_sigchld.sa_sigaction != NULL) {
            original_sigchld.sa_sigaction(sig, info, context);
        }
    } else {
        if (original_sigchld.sa_handler != NULL &&
            original_sigchld.sa_handler != SIG_DFL &&
            original_sigchld.sa_handler != SIG_IGN) {
            original_sigchld.sa_handler(sig);
        }
    }

    // Let Ruby also handle it (it will reap its own child processes)
    // Ruby's handler is now installed - we don't call it directly,
    // just let signal propagate if needed
}

/**
 * Setup compromise signal handling
 */
static void SetupCompromiseSignalHandlers(void) {
    struct sigaction sa;
    memset(&sa, 0, sizeof(sa));

    // Setup chained SIGCHLD handler
    sa.sa_flags = SA_SIGINFO | SA_RESTART;
    sigemptyset(&sa.sa_mask);
    sa.sa_sigaction = ChainedSigchldHandler;

    if (sigaction(SIGCHLD, &sa, NULL) != 0) {
        fprintf(stderr, "Failed to setup chained SIGCHLD handler\n");
    }
}
#endif

// Fetch the three Ruby log-stream FDs from the logging subsystem; on any
// failure fall back to the process's real stdout/stderr so the VM can
// still produce output even without the logging system initialized.
static void setup_log_fds(int* ruby_stdout_fd, int* ruby_stderr_fd, int* vmlogger_fd) {
    *ruby_stdout_fd = logging_get_stream_fd(LOG_STREAM_RUBY_STDOUT);
    *ruby_stderr_fd = logging_get_stream_fd(LOG_STREAM_RUBY_STDERR);
    *vmlogger_fd    = logging_get_stream_fd(LOG_STREAM_VMLOGGER);

    if (*ruby_stdout_fd < 0 || *ruby_stderr_fd < 0 || *vmlogger_fd < 0) {
        fprintf(stderr, "Failed to get log stream file descriptors: stdout=%d, stderr=%d, vmlogger=%d\n",
                *ruby_stdout_fd, *ruby_stderr_fd, *vmlogger_fd);
        *ruby_stdout_fd = STDOUT_FILENO;
        *ruby_stderr_fd = STDERR_FILENO;
        *vmlogger_fd    = STDERR_FILENO;
    }
}

// Set RUBY_DEBUG_* env vars BEFORE ruby_options so the debug gem's config
// (read inside DEBUGGER__.open) picks them up. The matching
// `require 'debug/open'` must run AFTER ruby_options so $LOAD_PATH is
// populated from RUBYLIB; that's what arm_remote_debug_listener does.
static void setenv_remote_debug(const RubyVMRemoteDebugOptions* opts) {
    char port_str[16];
    snprintf(port_str, sizeof(port_str), "%d", opts->port);
    setenv("RUBY_DEBUG_HOST",    opts->host,  1);
    setenv("RUBY_DEBUG_PORT",    port_str,    1);
    setenv("RUBY_DEBUG_COOKIE",  opts->token, 1);
    setenv("RUBY_DEBUG_NONSTOP", "1",         1);
    if (opts->session_name) {
        setenv("RUBY_DEBUG_SESSION_NAME", opts->session_name, 1);
    }
}

// Same env-before-options pattern for the eval listener. RemoteEval.start
// reads these via ENV[...] at runtime.
static void setenv_remote_eval(const RubyVMRemoteEvalOptions* opts) {
    char port_str[16];
    snprintf(port_str, sizeof(port_str), "%d", opts->port);
    setenv("REMOTE_EVAL_HOST",  opts->host,  1);
    setenv("REMOTE_EVAL_PORT",  port_str,    1);
    setenv("REMOTE_EVAL_TOKEN", opts->token, 1);
    if (opts->session_name) {
        setenv("REMOTE_EVAL_SESSION_NAME", opts->session_name, 1);
    }
}

// Arm the Ruby `debug` gem's TCP listener now that $LOAD_PATH has been
// built up by ruby_options. Failure is non-fatal — the VM continues even
// if the debugger can't start.
static void arm_remote_debug_listener(const RubyVMRemoteDebugOptions* opts) {
    int state = 0;
    rb_eval_string_protect("require 'debug/open'", &state);
    if (state != 0) {
        report_ruby_eval_error("start remote debugger");
    } else {
        fprintf(stderr, "[Ruby VM] Remote debugger listening on %s:%d\n",
                opts->host, opts->port);
    }
}

// Always pre-load the RemoteEval module — defines `module RemoteEval`
// without starting any listener. This lets a *post-boot* call to
// ruby_interpreter_enable_remote_eval inject `RemoteEval.start(...)` via
// a sync script enqueue. Cost: ~7 KB of Ruby always parsed at boot,
// regardless of whether the eval listener is configured.
static void preload_remote_eval_module(void) {
    int state = 0;
    if (eval_embedded_script("remote_eval.rb", &state) != 0) {
        fprintf(stderr, "[Ruby VM] remote_eval.rb not embedded — eval listener unavailable\n");
    } else if (state != 0) {
        report_ruby_eval_error("define RemoteEval module");
    }
}

// Boot-time arming of the eval listener; only called if remote_eval was
// configured before ruby_vm_start. Post-boot enables go through the
// inject path in ruby-interpreter.c.
static void start_remote_eval_listener(const RubyVMRemoteEvalOptions* opts) {
    int state = 0;
    rb_eval_string_protect(
        "RemoteEval.start(host: ENV['REMOTE_EVAL_HOST'],"
        " port: Integer(ENV['REMOTE_EVAL_PORT']),"
        " token: ENV['REMOTE_EVAL_TOKEN'],"
        " session_name: ENV['REMOTE_EVAL_SESSION_NAME'])",
        &state);
    if (state != 0) {
        report_ruby_eval_error("start remote eval listener");
    } else {
        fprintf(stderr, "[Ruby VM] Remote eval listening on %s:%d\n",
                opts->host, opts->port);
    }
}

// Bring the Ruby C-API into a usable state: ruby_init, restore signal
// handlers we saved before (Android), wire static extensions, and load
// safe_runner. Must run inside the RUBY_INIT_STACK scope opened by the
// caller.
static void initialize_ruby_runtime(void) {
    ruby_init();

#ifdef RUBY_REDIRECT_SIGNALS
    // ruby_init overwrote signal handlers; restore Android-critical ones
    // and install our compromise handlers for shared signals.
    RestoreCriticalSignalHandlers();
    SetupCompromiseSignalHandlers();
    // Disable Ruby's SIGPIPE handler so writes to a closed peer fail with
    // EPIPE rather than killing the VM.
    rb_eval_string("Signal.trap('PIPE', 'SYSTEM_DEFAULT')\n");
#endif

    // CRITICAL: static-linked extensions need their Init_<name> called.
    // With --with-static-linked-ext (and no dynamic dlopen), `require 'X'`
    // for a built-in C ext only works once Init_X has run.
    Init_ext();
    if (g_custom_ext_init != NULL) {
        g_custom_ext_init();
    }

    // Load safe_runner.rb from memory and provide it so user scripts that
    // `require 'safe_runner'` get a no-op (the modules are already loaded).
    if (eval_embedded_script("safe_runner.rb", NULL) == 0) {
        rb_provide("safe_runner");
    }
}

static int run_main_vm_node(const char* baseDirectory,
                            const char* rubyExtraLoadPath,
                            const char* scriptContent,
                            int fromFilename,
                            int socket_fd,
                            const RubyVMRemoteDebugOptions* remote_debug,
                            const RubyVMRemoteEvalOptions* remote_eval)
{
    SetupRubyEnv(baseDirectory, rubyExtraLoadPath);

#ifdef RUBY_REDIRECT_SIGNALS
    // Save handlers BEFORE ruby_sysinit/ruby_init clobber them, so we can
    // re-install the ones Android needs (in initialize_ruby_runtime).
    SaveOriginalSignalHandlers();
#endif

    int ruby_stdout_fd, ruby_stderr_fd, vmlogger_fd;
    setup_log_fds(&ruby_stdout_fd, &ruby_stderr_fd, &vmlogger_fd);

    char socket_fd_str[32], ruby_stdout_fd_str[32], ruby_stderr_fd_str[32], vmlogger_fd_str[32];
    snprintf(socket_fd_str,        sizeof(socket_fd_str),        "%d", socket_fd);
    snprintf(ruby_stdout_fd_str,   sizeof(ruby_stdout_fd_str),   "%d", ruby_stdout_fd);
    snprintf(ruby_stderr_fd_str,   sizeof(ruby_stderr_fd_str),   "%d", ruby_stderr_fd);
    snprintf(vmlogger_fd_str,      sizeof(vmlogger_fd_str),      "%d", vmlogger_fd);

    int argc;
    char** argv = build_ruby_argv_va(&argc, scriptContent, fromFilename,
                                     4, socket_fd_str, ruby_stdout_fd_str, ruby_stderr_fd_str, vmlogger_fd_str);

    ruby_sysinit(&argc, &argv);
    {
        RUBY_INIT_STACK;

        initialize_ruby_runtime();

        // Pre-`ruby_options` env: both listener configs are read from ENV[]
        // either by the debug gem (via DEBUGGER__.open) or by RemoteEval.start.
        // ruby_options is what populates $LOAD_PATH from RUBYLIB; we set env
        // now and arm the listeners AFTER it returns.
        if (remote_debug != NULL) setenv_remote_debug(remote_debug);
        if (remote_eval  != NULL) setenv_remote_eval(remote_eval);

        void* options = ruby_options(argc, argv);

        // Listener arming (post-ruby_options). The eval module is always
        // pre-loaded so post-boot inject (from ruby-interpreter.c) can call
        // RemoteEval.start even when remote_eval wasn't configured at boot.
        if (remote_debug != NULL) arm_remote_debug_listener(remote_debug);
        preload_remote_eval_module();
        if (remote_eval  != NULL) start_remote_eval_listener(remote_eval);

        const int result = ruby_run_node(options);

        free_ruby_argv(argv, argc);
        return result;
    }
}


int ExecMainRubyVM(RubyVM* vm, const char* rubyDirectoryPath, const char* nativeLibsDirLocation) {
    const char* scriptContent = ruby_script_get_content(vm->main_script);
    const int commandsFd = vm->commands_channel.second_fd;

    return run_main_vm_node(rubyDirectoryPath, nativeLibsDirLocation, scriptContent, 0, commandsFd,
                            vm->remote_debug, vm->remote_eval);
}

int ExecRubyScriptInline(const char* rubyDirectoryPath,
                         const char* nativeLibsDirLocation,
                         const char* scriptFilePath) {
    return run_main_vm_node(rubyDirectoryPath, nativeLibsDirLocation,
                            scriptFilePath, 1, -1, NULL, NULL);
}
