# CMake script to update library-dependencies.c with extracted dependency list
# Called as a post-build step after extracting dependencies from the built library

if(NOT DEPS_LIST_FILE OR NOT DEPS_C_IN OR NOT DEPS_C_OUT)
    message(FATAL_ERROR "Required variables not set: DEPS_LIST_FILE, DEPS_C_IN, DEPS_C_OUT")
endif()

# Read the dependency list generated by extract_deps.sh
if(EXISTS ${DEPS_LIST_FILE})
    file(READ ${DEPS_LIST_FILE} DEPENDENCY_LIST)
    # Remove trailing whitespace/newlines
    string(STRIP "${DEPENDENCY_LIST}" DEPENDENCY_LIST)
else()
    set(DEPENDENCY_LIST "    /* No dependencies found */")
endif()

# Generate the C file from template
configure_file(${DEPS_C_IN} ${DEPS_C_OUT} @ONLY)

message(STATUS "Updated ${DEPS_C_OUT} with dependency information")
